// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuk-wkpALQhBkHTjclJGBpKkCKEYf_Sqg',
    appId: '1:580646667465:web:37f860524bf0cf326df918',
    messagingSenderId: '580646667465',
    projectId: 'insta-moment',
    authDomain: 'insta-moment.firebaseapp.com',
    storageBucket: 'insta-moment.appspot.com',
    measurementId: 'G-RYZBMDZ53J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9CSa5Yq6tZxwlpULAtMrWycNdHMh8xAY',
    appId: '1:580646667465:android:ae29725fbd0aac1c6df918',
    messagingSenderId: '580646667465',
    projectId: 'insta-moment',
    storageBucket: 'insta-moment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCqiURm_L8sG1djmtXdzylPa-wQf9KqBI',
    appId: '1:580646667465:ios:df2aa35ba72e744c6df918',
    messagingSenderId: '580646667465',
    projectId: 'insta-moment',
    storageBucket: 'insta-moment.appspot.com',
    iosBundleId: 'com.djzarka.test2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCqiURm_L8sG1djmtXdzylPa-wQf9KqBI',
    appId: '1:580646667465:ios:df2aa35ba72e744c6df918',
    messagingSenderId: '580646667465',
    projectId: 'insta-moment',
    storageBucket: 'insta-moment.appspot.com',
    iosBundleId: 'com.djzarka.test2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuk-wkpALQhBkHTjclJGBpKkCKEYf_Sqg',
    appId: '1:580646667465:web:f9c04c3ff0150abf6df918',
    messagingSenderId: '580646667465',
    projectId: 'insta-moment',
    authDomain: 'insta-moment.firebaseapp.com',
    storageBucket: 'insta-moment.appspot.com',
    measurementId: 'G-FBSP2Y8545',
  );

}